redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

production:
  adapter: redis
  url: redis://redistogo:a915533b6a24c21f09da36127a0366b4@spinyfin.redistogo.com:11319/
development: *redis
test: *redis
